config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'home#index'

  resources :lists, only: [:new, :create, :index, :edit, :update, :destroy] do
    resources :tasks, only: [:new, :create, :edit, :update, :destroy]

    member do
      get 'favorite'
    end
  end
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :user
  belongs_to :list

  validates :user, :list, presence: true
end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to  :user

  has_many    :tasks

  has_many :favorites
  has_many :favorite_users, through: :favorites

  accepts_nested_attributes_for :tasks

  validates :user, :name, presence: true

  scope :public_view,	  -> { where(private_visibility: false) }
  scope :public_or_own, -> (user_id) { where('user_id = ? or private_visibility = false', user_id) }

  def owner?(current_user)
    user == current_user
  end

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :list

  validates :title, :list, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists

  has_many :favorites
  has_many :favorite_lists, through: :favorites
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index

  def index
    @lists = List.public_view.order(created_at: :desc)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  respond_to :html, :js

  before_action :get_list, only: [:edit, :update, :destroy, :favorite]

  def index
    @lists = List.public_or_own(current_user.id).order(created_at: :desc, updated_at: :desc)
    respond_with @lists
  end

  def new
    @list = List.new
  end

  def create
    @list = current_user.lists.new(list_params)
    @list.save
  end

  def edit; end

  def update
    @list.update(list_params)
  end

  def destroy
    @list.destroy
  end

  def favorite
    @list.favorites.create(user: current_user)
    redirect_to lists_path
  end

  private

  def get_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :private_visibility)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :js

  before_action :get_list, only: [:new, :create, :edit]
  before_action :get_task, only: [:edit, :update, :destroy]

  def new
    @task = @list.tasks.new
  end

  def create
    @task = @list.tasks.new(task_params)
    flash[:notice] = "Task was successfully created." if @task.save
  end

  def edit; end

  def update
    @task.update(task_params)
  end

  def destroy
    @task.destroy
  end

  private

  def get_task
    @task = Task.find(params[:id])
  end

  def get_list
    @list = List.find(params[:list_id])
  end

  def task_params
    params.require(:task).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def greeting
    current_user.name || current_user.login || current_user.email
  end

  def label_favorite(list)
    current_user.favorites.map(&:list).include?(list) ? 'Favorited' : 'Favorite'
  end
end

app/views/home/index.html.erb
<div id='lists'>
  <%= render @lists %>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <h1 class="brand">ACME TASKLIST</h1>
  <h2><%= link_to '+ List', new_list_path, remote: true if user_signed_in? %></h2>
  <div class="account">
    <% if user_signed_in? %>
      <h3><%= greeting %></h3>
      <h3><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></h3>
    <% else %>
      <h3><%= link_to 'Login', new_user_session_path %></h3>
    <% end %>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Acme TaskLists</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/navbar' %>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for @list, remote: true do |f| %>
  <%= f.input :name %>
  <%= f.input :private_visibility, as: :boolean, label: 'Private?', inline_label: true  %>
  <%= f.button :submit %>
<% end %>

app/views/lists/_list.html.erb
<%= div_for list do %>
  <div class="title">
    <strong><%= list.name %></strong>
    <span class="right">
      <%= link_to label_favorite(list), favorite_list_path(list), remote: true if user_signed_in? && !list.owner?(current_user) %>
      <%= link_to 'Add task', new_list_task_path(list), remote: true if list.owner?(current_user) %>
    </span>
  </div>
  <div class='actions'>
    <% if list.owner?(current_user) %>
      <%= link_to 'edit', edit_list_path(list), remote: true %>
      <%= link_to 'delete', list, method: :delete, data: {confirm: "Delete #{list.name}?"}, remote: true %>
    <% end %>
  </div>
  <div id='tasks'>
    <%= render list.tasks %>
  </div>
<% end %>

app/views/lists/create.js.erb
$('form').hide();
$('#lists').prepend('<%= j render partial: "list", locals: {list: @list} %>');

app/views/lists/destroy.js.erb
$('div#<%= dom_id(@list) %>').toggle('slow').remove();

app/views/lists/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@list) %>').replaceWith('<%= j render("form") %>');

app/views/lists/index.html.erb
<div id="lists">
  <%= render @lists %>
</div>

app/views/lists/new.js.erb
$('#lists').first().before('<%= j render("form") %>');

app/views/lists/update.js.erb
$('form').replaceWith('<%= j render partial: "list", locals: {list: @list} %>');

app/views/tasks/_form.html.erb
<%= simple_form_for [@list, @task], remote: true do |f| %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/tasks/_task.html.erb
<%= div_for task do %>
  <li>
    <%= task.title %>
    <div class='actions'>
      <% if user_signed_in? && task.list.owner?(current_user) %>
        <%= link_to 'edit', edit_list_task_path(task.list, task), remote: true %>
        <%= link_to 'delete', [task.list, task], method: :delete, remote: true %>
      <% end %>
    </div>
  </li>
<% end %>

app/views/tasks/create.js.erb
$('form').hide();
$('#tasks').prepend('<%= j render partial: "task", locals: {task: @task} %>');

app/views/tasks/destroy.js.erb
$('div#<%= dom_id(@task) %>').toggle('slow').remove();;

app/views/tasks/edit.html.erb
<%= render 'form' %>

app/views/tasks/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render("form") %>');

app/views/tasks/new.html.erb
<%= render 'form' %>

app/views/tasks/new.js.erb
$('div#<%= dom_id(@list) %> #tasks').before('<%= j render("form") %>');

app/views/tasks/update.js.erb
$('form').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');